POST https://panda-market-api.vercel.app/products
Content-Type: application/json

{
  "images": [
    "https://i.pinimg.com/474x/e5/ca/2d/e5ca2d4b0359bdfb97f3c1c7a2602076.jpg"
  ],
  "tags": [
    "디자인"
  ],
  "price": 140000,
  "description": "디자인 헬로우",
  "name": "쇼룸 디자인 헬로우"
}